"""Shared constants for the voice biometrics system."""

# Authentication constants
DEFAULT_SIMILARITY_THRESHOLD = 0.85
DEFAULT_SPOOF_THRESHOLD = 0.3
DEFAULT_PHRASE_MATCH_THRESHOLD = 0.8

# Retention policy defaults
DEFAULT_RETENTION_DAYS = 7
MAX_RETENTION_DAYS = 365

# Challenge configuration
CHALLENGE_EXPIRY_MINUTES = 10
MIN_PHRASE_LENGTH = 10
MAX_PHRASE_LENGTH = 50

# Audio processing
SUPPORTED_AUDIO_FORMATS = ["wav", "mp3", "flac", "m4a"]
MAX_AUDIO_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
MIN_AUDIO_DURATION_SEC = 2.0
MAX_AUDIO_DURATION_SEC = 30.0

# Model dimensions
EMBEDDING_DIMENSION = 256

# API limits
DEFAULT_RATE_LIMIT = 100  # requests per hour per client
MAX_ENROLLMENT_SAMPLES = 6
MIN_ENROLLMENT_SAMPLES = 3

# Latency SLA
MAX_INFERENCE_LATENCY_MS = 5000
MAX_TOTAL_LATENCY_MS = 10000

# Security
API_KEY_LENGTH = 32
ENCRYPTION_KEY_LENGTH = 32